### ISSUE TITLE
Ability to get the width of rendered text

### ISSUE THREAD

**Issue by ekner** [CookieShade/BETA.js#15]
As this feature still hasn't been implemented in advanced.js, I will try here.

This can be done with the measureText member function:
`context2D.measureText(text).width;`

The feature could be implemented by making a separate function which takes a size argument, and the actual text. However, this approach requires the user to first run the function which renders the text, then a similar function where one has to enter the text and size again, to get the width. An alternative method could be to make the text rendering function return the width of the rendered text, so the user can use it like this:

`var width = renderer.text(pos, text, font, size, color);`

**Comment by CookieShade** [comment]
Good idea, I'll make sure to implement text metrics in the not-too-distant future.

However, since a common use case for text metrics is to center text, or align text with something else, it makes little sense to require the text to be rendered first before granting access to the width.

I think it's preferable to have measurement be its own function, e.g.:
`var width = renderer.getTextWidth(text, font, size);`

Unfortunately, width is the only metric available, all the others have essentially [nonexistant support](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics#Browser_compatibility).

**Comment by ekner** [comment]
Great.
